version: '3.8'

services:
  main-server:
    image: management-system/main-server:latest
    ports:
      - "8080:8080"
    volumes:
      - main_server_data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - management_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  regular-node:
    image: management-system/regular-node:latest
    ports:
      - "8081:8081"
    volumes:
      - node_data:/opt/node-updates
      - node_backups:/opt/node-backups
      - node_logs:/var/log/node-agent
    environment:
      - PYTHONPATH=/app
      - MAIN_SERVER_URL=http://main-server:8080
    networks:
      - management_network
    deploy:
      mode: global  # Deploy on every node
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 128M
          cpus: '0.05'

volumes:
  main_server_data:
    driver: local
  node_data:
    driver: local
  node_backups:
    driver: local
  node_logs:
    driver: local

networks:
  management_network:
    driver: overlay
    attachable: true

